// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package csv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the filePath and tableName
type ImportDataRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TableName            string   `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportDataRequest) Reset()         { *m = ImportDataRequest{} }
func (m *ImportDataRequest) String() string { return proto.CompactTextString(m) }
func (*ImportDataRequest) ProtoMessage()    {}
func (*ImportDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ImportDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportDataRequest.Unmarshal(m, b)
}
func (m *ImportDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportDataRequest.Marshal(b, m, deterministic)
}
func (m *ImportDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportDataRequest.Merge(m, src)
}
func (m *ImportDataRequest) XXX_Size() int {
	return xxx_messageInfo_ImportDataRequest.Size(m)
}
func (m *ImportDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportDataRequest proto.InternalMessageInfo

func (m *ImportDataRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ImportDataRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

// The response message containing the
type ImportDataReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportDataReply) Reset()         { *m = ImportDataReply{} }
func (m *ImportDataReply) String() string { return proto.CompactTextString(m) }
func (*ImportDataReply) ProtoMessage()    {}
func (*ImportDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ImportDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportDataReply.Unmarshal(m, b)
}
func (m *ImportDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportDataReply.Marshal(b, m, deterministic)
}
func (m *ImportDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportDataReply.Merge(m, src)
}
func (m *ImportDataReply) XXX_Size() int {
	return xxx_messageInfo_ImportDataReply.Size(m)
}
func (m *ImportDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_ImportDataReply proto.InternalMessageInfo

func (m *ImportDataReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ImportDataRequest)(nil), "csv.ImportDataRequest")
	proto.RegisterType((*ImportDataReply)(nil), "csv.ImportDataReply")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2e, 0x2e, 0x53, 0xf2,
	0xe5, 0x12, 0xf4, 0xcc, 0x2d, 0xc8, 0x2f, 0x2a, 0x71, 0x49, 0x2c, 0x49, 0x0c, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x48, 0xcb, 0xcc, 0x49, 0xf5, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x4b, 0x12, 0x93, 0xa0,
	0x92, 0x4c, 0x60, 0x49, 0x84, 0x80, 0x92, 0x36, 0x17, 0x3f, 0xb2, 0x71, 0x05, 0x39, 0x95, 0x42,
	0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0xb3, 0x60, 0x5c, 0x23, 0x2f, 0x2e,
	0xae, 0xe0, 0xc2, 0x9c, 0x60, 0x88, 0xa3, 0x84, 0x6c, 0xb8, 0xb8, 0x10, 0x5a, 0x85, 0xc4, 0xf4,
	0x92, 0x8b, 0xcb, 0xf4, 0x30, 0x9c, 0x26, 0x25, 0x82, 0x21, 0x5e, 0x90, 0x53, 0xa9, 0xc4, 0x90,
	0xc4, 0x06, 0xf6, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x67, 0x26, 0xb3, 0xe4, 0x00,
	0x00, 0x00,
}
